### ISSUE TITLE
HTML anchors in the Reference page

### ISSUE THREAD

**Issue by futuremarc** [processing/p5.js-website#139]
It'd be a really nice small thing for the sake of tutorials or guides to be able to link to certain sections of the reference. Just like hovering the sections [here](https://www.polymer-project.org/1.0/docs/start/getting-the-code.html#using-zip).

**Comment by workergnome** [comment]
Can you give an example of a place in the reference where this would be useful, just so we're on the same page (literally)?

**Comment by gnclmorais** [comment]
@futuremarc, that would only work if you would be already on the page, not if you refresh the page (for example), because of the way this page is loaded. The IDs are in place, it’s just a matter of 1) turning the page static (issue #143 might be of interest for this) and 2) making the links available.

**Comment by futuremarc** [comment]
Very true. Not sure this issue is a priority enough to keep this open. I'm closing this.
