### ISSUE TITLE
Examples that use api.openweathermap.org now broken

### ISSUE THREAD

**Issue by Jared-Sprague** [processing/p5.js-website#172]
api.openweathermap.org now requires an api key:
http://api.openweathermap.org/data/2.5/weather?q=London,UK

This breaks examples like loadJSON, they are stuck in 'loading...'  as we would expect:
http://p5js.org/reference/#/p5/loadJSON

I think the most reliable way to fix this is to us a static json file hosted with the examples.  

What do you think?

**Comment by lmccart** [comment]
sigh :( what do we think about just making a key for p5js.org and using it in the examples? I know that's not great practice, but I can't imagine too much damage coming from that. worst case scenario seems the key could get revoked, in which case we could then switchover to static json... it is just so nice to have live data examples up there.

**Comment by Jared-Sprague** [comment]
I think that sounds fine as long as the key is associated with the request in a way that doesn't over complicate the example.

I think the live example is more compelling that a static json file.

**Comment by shiffman** [comment]
I agree, I would sign up for a key for the online examples.  I'm doing this for lots of things I'm posting for various courses (albeit with a smaller audience) and so far the sun is still rising and setting.

One thing I'll add is that the NYTimes API seems to work with "sample-key" so that might be an option for an additional example.  I am preparing more examples so would be glad to add one.
