### ISSUE TITLE
p5.Pulse example keeps playing after navigating back

### ISSUE THREAD

**Issue by toolness** [processing/p5.js-website#186]
1. Go to the [p5.sound reference page](http://p5js.org/reference/#/libraries/p5.sound)
2. Click on the "p5.Pulse" link
3. After the sound starts playing, press your browser's back button
4. The pulse is still playing!! (At least on Firefox and Chrome)

I thought this was a duplicate of #37, but that's been marked as fixed, so I'm not sure what's going on...

**Comment by therewasaguy** [comment]
The back button is not actually navigating away from the page, just changing the url hash. So the issue seems to be that the hash change event is no longer calling ``remove`` on active p5 instances.

I got this working at one point, and it might've been removed for a good reason that I'm not aware of. But I think something like this is needed (especially for the p5.sound reference pages that make noise!). So I just sent a PR that would bring it back.

If you wanna test this out, you can add  ```if (frameCount > 20) remove();``` to the draw loop on [that example](http://p5js.org/reference/#/p5.Pulse)—it makes the sound stop and the sketch go away. But if you add a console.log to the draw loop, and navigate around, it keeps on loggin'...

Good ear, @toolness!
