### ISSUE TITLE
Left Sidebar Hides Elements

### ISSUE THREAD

**Issue by hkirat** [processing/p5.js-website#202]
Not sure if this happens on every browser but if you go to http://p5js.org/reference/ and scroll down, the left sidebar also scrolls down always hiding github and twitter links.
Though it doesn't happen on other pages but happens on all pages of the form http://p5js.org/reference/*
eg:
http://p5js.org/reference/#/p5/windowResized
Screenshot
![screenshot from 2015-12-02 14 41 41](https://cloud.githubusercontent.com/assets/8079861/11526812/15be78a8-9903-11e5-86e1-a59819b26d18.png)

**Comment by limzykenneth** [comment]
I think the problem is [here](https://github.com/processing/p5.js-website/blob/master/js/scroll.js) on line 36, the `offset.top` should be zero but remains the same. However, I don't think simply changing it to be 0 will help as that I think was added so that it doesn't overlap with the p5.js logo at the top when just a little is scrolled.
