### ISSUE TITLE
Add a 'Supporters' section on 'About' page

### ISSUE THREAD

**Issue by Qianqianye** [processing/p5.js-website#369]
We'd like to add a 'Supporters' section on 'About' page right after 'Processing Foundation' section. What's the best way to add it? 
the current set up of the page makes it a bit hard to edit. As a main page, the 'About' page is currently hidden in text-detail folder. We'd like to rethink the file location in the future.

CC @outofambit @davepagurek @limzykenneth @ccanash

**Comment by outofambit** [comment]
Hey @Qianqianye, the About page is a little bit of a special case. The paragraph part of the content is in the text-detail collection as you noticed, and the bottom half of the page is defined in [`AboutLayout.astro`](https://github.com/processing/p5.js-website/blob/main/src/layouts/AboutLayout.astro) because it is primarily generated from the contents of the people collection.

To add a new section to that page I would add a new `<section>` in [`AboutLayout.astro` just before closing `</BaseLayout>` tag](https://github.com/processing/p5.js-website/blob/67cbc8901671420a4c18ad9e9e372651b3228505/src/layouts/AboutLayout.astro#L118-L119) with that list of supporters. You could probably copy the "Processing Foundation" section and edit it accordingly.
