### ISSUE TITLE
Expected search results missing under Reference section

### ISSUE THREAD

**Issue by meezwhite** [processing/p5.js-website#458]
### Most appropriate sections of the p5.js website?

Reference

### What is your operating system?

None

### Actual Behavior

I was searching for "color" or "color()" using the website search.

Under the "Reference" section, the first suggestion is "color". However, this links to [p5.Framebuffer/color](https://p5js.org/reference/p5.Framebuffer/color), but there is no result linking to the [color() reference page](https://p5js.org/reference/p5/color/).

### Expected Behavior

I was expecting "color" to link to the [color() reference page](https://p5js.org/reference/p5/color/).

### Steps to reproduce

1. Search for "color" or "color()" using the website search, or follow this link: https://p5js.org/search/?term=color
2. Click on "color" under "Reference" section.

### Would you like to work on the issue?

Unsure

**Comment by meezwhite** [comment]
This issue also affects other search queries e.g.:
* `get` or `get()` shows result for [p5.TypedDict/get](https://p5js.org/reference/p5.TypedDict/get), however no result for [pixels `get()` function](https://p5js.org/reference/p5/get)
* `set` or `set()` shows result for [p5.Vector/set/](https://p5js.org/reference/p5.Vector/set), however no results for [pixels `get()` function](https://p5js.org/reference/p5/set) or [p5.TypedDict/set function](https://p5js.org/reference/p5.TypedDict/set)

**Comment by Qianqianye** [comment]
Thanks @meezwhite! 
I'm tagging the web developer consultants @outofambit @stalgiag to take a look at this. The global search is a bit buggy when it comes to entries that have same names (but in different places), like color, get, set, mousePressed, as mentioned in earlier part of this issue. Could you share some insights on this? Thank you!

cc @limzykenneth

**Comment by stalgiag** [comment]
Ah that makes sense! It looks like the script for parsing the search index uses [the title from the content](https://github.com/processing/p5.js-website/blob/main/src/scripts/builders/search.ts#L238) when building the reference search index. The title in the reference content items does not include the class name as the standalone method name is used on the Reference index page and that item's status as a member method is derived from the content file location rather than the title. As a result, the search index will overwrite any previous references with that same title in [this line](https://github.com/processing/p5.js-website/blob/main/src/scripts/builders/search.ts#L269). The to-do would be to include the class name in the title for the reference items. There are several approaches to getting the class name from the file item in that script.

This can be fixed by editing the file I linked above based on the directions given in that paragraph and running `npm run build:search` in your local to rebuild the search indices. If any contributors want to take this on, I can advise and assist. If no contributors volunteer, I can tackle it sometime in the next week.

**Comment by Souvik-Cyclic** [comment]
I would like to work on this, you can assign this to me. @stalgiag

**Comment by meezwhite** [comment]
@stalgiag thank you for the explanation. I'd rather leave this up to you this time; there are still some decisions to be made regarding how to display two entries (e.g. functions) with the same name, such as:
* pixels > set()
* p5.Vector > set()

It would also be nice to update the breadcrumbs, but that's maybe for another issue.

**Comment by Qianqianye** [comment]
Closing this issue since it's fixed in #472
