### ISSUE TITLE
wrong link on "submit a pull request on GitHub!"

### ISSUE THREAD

**Issue by arjunmakesthings** [processing/p5.js-website#482]
### Most appropriate sections of the p5.js website?

Community (Sketches, Libraries, Events)

### What is your operating system?

Mac OS

### Actual Behavior

the button redirects to a 404 - page not found: https://github.com/processing/p5.js-website/blob/main/contributing_libraries.md

### Expected Behavior

should take me to the page that shows me how to submit the pull request

### Would you like to work on the issue?

can work on it

**Comment by Divyansh013** [comment]
I think this is the [link](https://github.com/processing/p5.js/blob/main/contributor_docs/contributor_guidelines.md#pull-requests) you are looking for

**Comment by Qianqianye** [comment]
Thanks @arjunmakesthings and @Divyansh013. This bug is fixed in this [commit](https://github.com/processing/p5.js-website/commit/abf556cc7c55da493c4d4fd1936ff4163c464709), so the 'submit a pull request on GitHub' link on [p5js.org/libraries](https://p5js.org/libraries) page is working now.
I'm closing this issue for organizational purpose. Feel free to reopen it if you have any other questions. Thank you!
