### ISSUE TITLE
 Fix broken links on p5.js website page for "Contributing to the p5.js Reference"

### ISSUE THREAD

**Issue by iamniky** [processing/p5.js-website#509]
### Most appropriate sections of the p5.js website?

Contribute

### What is your operating system?

Windows

### Web browser and version

Firefox v130.0, though would affect all.

### Actual Behavior

When users visit the URL https://p5js.org/contribute/contributing_to_the_p5js_reference/ and click on the hyperlink that is labeled "web accessibility contributor documentation", they are met with a 404 error page:

![Screenshot 2024-09-06 001800](https://github.com/user-attachments/assets/e542532d-1894-4395-9dab-8b7b99de778f)

![Screenshot 2024-09-06 000726](https://github.com/user-attachments/assets/c4260075-0c6d-43ee-a537-29484e1975d0)

This same issue happens when the users click on the hyperlink labeled "contributor guidelines". They receive a 404 error page:

![Screenshot 2024-09-06 001712](https://github.com/user-attachments/assets/f954a6a9-4091-4916-b5d4-573ec0ba9e8e)

![Screenshot 2024-09-06 001119](https://github.com/user-attachments/assets/9865e0fc-be2c-4031-a3df-70dcf737a84f)

### Expected Behavior

We expect that when the users click the hyperlink labeled "web accessibility contributor documentation", they are taken to a page with information regarding web accessibility contributor documentation.

We expect that when the users click the hyperlink labeled "contributor guidelines", they are taken to a page with information regarding contributor guidelines.

### Steps:

    1. Go to https://p5js.org/contribute/contributing_to_the_p5js_reference/
    2. Click on respective links (listed in table below).
    3. Get a 404 error.

### Solution:

    Replace listed broken links to the correct links.

|Source link text: | Current link: | Suggested link:
|-- | -- | --|
| web accessibility contributor documentation | https://p5js.org/contributor-docs/#/web_accessibility?id=user-generated-accessible-canvas-descriptions | https://p5js.org/contribute/web_accessibility/ |
| contributor guidelines | https://github.com/processing/p5.js/blob/main/contributor_docs/contributor_guidelines/ | https://p5js.org/contribute/contributor_guidelines/ |

### Would you like to work on the issue?

Yes, I'd like to work on the issue.

**Comment by shourysingh07** [comment]
I'd like to work on the issue.

**Comment by Qianqianye** [comment]
Thank you @iamniky and @shourysingh07. As mentioned in PR #514, the broken links mentioned  are fixed in this [commit](https://github.com/processing/p5.js/commit/69654165dc37d70b2ca5c6887b33772cec6138e6) and this [commit](https://github.com/processing/p5.js/commit/ab9becfc1428bdacbf450ce2f7de32637869cfca) within p5.js library repo. The updates are now reflected on the [contributing_to_the_p5js_reference.mdx](https://github.com/processing/p5.js-website/blob/main/src/content/contributor-docs/en/contributing_to_the_p5js_reference.mdx?plain=1) file and [Contributing to the p5.js Reference](https://p5js.org/contribute/contributing_to_the_p5js_reference/) web page.
