### ISSUE TITLE
Fix broken links on p5.js website page for "WebGL Contribution Guide"

### ISSUE THREAD

**Issue by iamniky** [processing/p5.js-website#510]
### Most appropriate sections of the p5.js website?

Contribute

### What is your operating system?

Windows

### Web browser and version

Firefox v130.0, though would affect all.

### Actual Behavior

When users visit the URL https://p5js.org/contribute/webgl_contribution_guide/ and click on the hyperlink that is labeled "contributor guidelines", they are met with a 404 error page:

![Screenshot 2024-09-06 003102](https://github.com/user-attachments/assets/e23f7546-a850-4f27-8cdc-46227dacd103)

![Screenshot 2024-09-06 003145](https://github.com/user-attachments/assets/568864c9-0101-43f9-843c-c5d965a437bb)

When users visit the URL https://p5js.org/contribute/webgl_contribution_guide/ and click on the hyperlink that is labeled "in a GitHub Project", they are met with a 404 error page:

![Screenshot 2024-09-06 003533](https://github.com/user-attachments/assets/b7b73fd6-3a89-48ee-9bbd-f9e5554bca6d)

![Screenshot 2024-09-06 003605](https://github.com/user-attachments/assets/b32d6474-e8e3-426c-baa8-34a2c12b8c67)

### Expected Behavior

We expect that when the users click the hyperlink labeled "contributor guidelines", they are taken to a page with information regarding contributor guidelines.

We expect that when the users click the hyperlink labeled "in a GitHub Project", they are taken to a page with information regarding a GitHub Project.

### Steps:

1. Go to https://p5js.org/contribute/contributing_to_the_p5js_reference/
2. Click on respective links (listed in table below).
3. Get a 404 error.

### Solution:

Replace listed broken links to the correct links.

Source link text: | Current link: | Suggested link:
-- | -- | --
contributor guidelines | https://github.com/processing/p5.js/blob/main/contributor_docs/contributor_guidelines/ | https://p5js.org/contribute/contributor_guidelines/
in a GitHub Project | https://github.com/orgs/processing/projects/5 | ???

### Would you like to work on the issue?

Yes, I'd like to work on the issue.

**Comment by iamniky** [comment]
Incorrect URL above under "Steps:"

It should be 

Steps:

    Go to  https://p5js.org/contribute/webgl_contribution_guide/
    Click on respective links (listed in table below).
    Get a 404 error.

**Comment by shourysingh07** [comment]
I'd like to work on the issue.

**Comment by Qianqianye** [comment]
Thanks @iamniky for catching the bug and @shourysingh07 for your interest in working on this.

The first link is already fixed in [this commit](https://github.com/processing/p5.js-website/commit/47f70a90816909925c153dfd8c30b2791f02157b#diff-13bb5858eaf21cd18b9d6d74f21d11ac417f7dc8f59f2a390a4cdcdef93f787e). 

The second link 'We organize open issues in a GitHub Project' should go to this link: https://github.com/orgs/processing/projects/20. If you are interested in working on this issue, please edit [this line](https://github.com/processing/p5.js/blob/main/contributor_docs/webgl_contribution_guide.md?plain=1#L19) in the p5.js repo [contributor_docs/webgl_contribution_guide.md](https://github.com/processing/p5.js/blob/main/contributor_docs/webgl_contribution_guide.md) file. Thanks!

**Comment by shourysingh07** [comment]
Thank you @Qianqianye ! I've opened a pull request within the [p5.js library repo](https://github.com/processing/p5.js).

Here is the [PR Link](https://github.com/processing/p5.js/pull/7263).

**Comment by Qianqianye** [comment]
Closing this issue since it's resolved in PR [#7263](https://github.com/processing/p5.js/pull/7263)
