### ISSUE TITLE
 Fix broken link on p5.js website page for "Our Focus on Access"

### ISSUE THREAD

**Issue by iamniky** [processing/p5.js-website#513]
### Most appropriate sections of the p5.js website?

Home

### What is your operating system?

Windows

### Web browser and version

Firefox v130.0, though would affect all.

### Actual Behavior

When users visit the URL https://p5js.org/contribute/access/ and click on the hyperlink that is labeled "2019 Contributors Conference", they are met with a 404 error page:

![Screenshot 2024-09-06 012317](https://github.com/user-attachments/assets/5dd4f634-c797-4449-8436-5bb91d6b7536)

![Screenshot 2024-09-06 012406](https://github.com/user-attachments/assets/57260812-8352-4787-bdcf-14e223586f26)

When users visit the URL https://p5js.org/contribute/access/ and click on the hyperlink that is labeled "p5.js Access Day 2022", they are met with a 404 error page:

![Screenshot 2024-09-06 012745](https://github.com/user-attachments/assets/c246d376-5d24-4fc9-a291-0b25d17de234)

![Screenshot 2024-09-06 012842](https://github.com/user-attachments/assets/7a699625-01e1-4b61-9540-efdbe2d62174)

### Expected Behavior

We expect that when the users click the hyperlink labeled "2019 Contributors Conference", they are taken to a page with information regarding the 2019 Contributors Conference.

We expect that when the users click the hyperlink labeled "p5.js Access Day 2022", they are taken to a page with information regarding p5.js Access Day 2022.

### Steps:

1. Go to https://p5js.org/contribute/access/
2. Click on respective links (listed in table below).
3. Get a 404 error.

### Solution:

Replace listed broken links to the correct links.

Source link text: | Current link: | Suggested link:
-- | -- | --
2019 Contributors Conference | https://p5js.org/community/contributors-conference-2019.html | https://p5js.org/events/contributors-conference-2019/
p5.js Access Day 2022 | https://p5js.org/community/p5js-access-day-2022.html | https://p5js.org/events/p5js-access-day-2022/

### Would you like to work on the issue?

Yes, I'd like to work on the issue.

**Comment by shourysingh07** [comment]
I'd like to work on the issue.

**Comment by Qianqianye** [comment]
Thanks @iamniky for reporting the bug. To share some context, the [contribute](https://p5js.org/contribute/) pages on p5js.org website are built directly from p5.js library repo [contributor_docs](https://github.com/processing/p5.js/tree/main/contributor_docs) folder, using a [script](https://github.com/processing/p5.js-website/blob/main/docs/scripts.md). So if we want to make changes, we will edit the docs in p5.js library repo [contributor_docs](https://github.com/processing/p5.js/tree/main/contributor_docs) folder.

The p5.js Access Day 2022 link is already fixed in this [commit](https://github.com/processing/p5.js/commit/5909c9d0a08fc14077d24690cf6384c442ba7d25) within p5.js library repo.

Hi @shourysingh07, if you are interested in working on this issue, please feel free to open a PR within [p5.js library repo](https://github.com/processing/p5.js), and fix the 2019 Contributors Conference link to https://p5js.org/events/contributors-conference-2019. After it's fixed, I will run the script `npm run build:contributor-docs` to build the page based on the updated doc. Thank you!

**Comment by shourysingh07** [comment]
Thank You @Qianqianye ! I've opened a pull request within [p5.js library repo](https://github.com/processing/p5.js).

Here is the [PR Link](https://github.com/processing/p5.js/pull/7255).

**Comment by Qianqianye** [comment]
Closing this issue since it's fixed in PR [#7255](https://github.com/processing/p5.js/pull/7255) in p5.js repo
