### ISSUE TITLE
In the reference section can we have syntax a bit on top, atleast above examples ?

### ISSUE THREAD

**Issue by ashish1729** [processing/p5.js-website#582]
### Topic

This might be personal usage but most of the time I go to the reference page for a function I am trying to take a quick look at the syntax so that I can copy it.

But currently, syntax is at the bottom of the page and sometimes there are many examples above it.

I want to bring this point up to see if others might be interested in having the syntax section at the top of the page

what I was thinking for the section structure

1. one or two-line short introduction for the function
2. Syntax which can be copy pasted
3. More detailed explanation of the function
4. Examples

**Comment by ashish1729** [comment]
also the description many times refer to things ( mostly parameters ) which are shown in the syntax later

**Comment by limzykenneth** [comment]
For me it is more of the opposite in that it is more common to copy from the examples rather than the detailed syntax description. A very common use case of the examples is to copy wholesale from it, knowing that it will work out of the box, before modifying it for the user's own use case. I would say there is definitely a case to be made that example is more important than the detailed descriptions of the syntax and parameters.

**Comment by ashish1729** [comment]
thank you for taking a look at my issue and sharing your thoughts. This is a weakly held opinion from my side, so I will close this issue.
