### ISSUE TITLE
Reference shows html entity &amp; rather than ampersand

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js-website#587]
https://p5js.org/reference/p5/if/

![image](https://github.com/user-attachments/assets/81a7b6d5-1b73-4994-ab14-a402162a0e7d)

### Most appropriate sections of the p5.js website?

Reference

### What is your operating system?

Mac OS

### Web browser and version

Firefox 131.0 (64-bit)

### Actual Behavior

HTML entity code is shown

### Expected Behavior

actual character should be shown

### Steps to reproduce

visit and look

### Would you like to work on the issue?

no

**Comment by shibomb** [comment]
I have found similar HTML escapes and incorrect tags.
I would be happy to help in resolving this issue.

### Boolean.mdx

https://github.com/processing/p5.js-website/blob/c4eea2e2a4162b8cec7854733194c6ede183bd2e/src/content/reference/en/p5/types/Boolean.mdx?plain=1#L91

https://github.com/processing/p5.js-website/blob/c4eea2e2a4162b8cec7854733194c6ede183bd2e/src/content/reference/en/p5/types/Boolean.mdx?plain=1#L124

https://github.com/processing/p5.js-website/blob/c4eea2e2a4162b8cec7854733194c6ede183bd2e/src/content/reference/en/p5/types/Boolean.mdx?plain=1#L142-L143

https://github.com/processing/p5.js-website/blob/c4eea2e2a4162b8cec7854733194c6ede183bd2e/src/content/reference/en/p5/types/Boolean.mdx?plain=1#L153

### Number.mdx

https://github.com/processing/p5.js-website/blob/c4eea2e2a4162b8cec7854733194c6ede183bd2e/src/content/reference/en/p5/types/Number.mdx?plain=1#L99

https://github.com/processing/p5.js-website/blob/c4eea2e2a4162b8cec7854733194c6ede183bd2e/src/content/reference/en/p5/types/Number.mdx?plain=1#L111

https://github.com/processing/p5.js-website/blob/c4eea2e2a4162b8cec7854733194c6ede183bd2e/src/content/reference/en/p5/types/Number.mdx?plain=1#L125


### see
https://p5js.org/reference/p5/Boolean/
![スクリーンショット 2024-10-17 19 20 38](https://github.com/user-attachments/assets/7f151606-65f5-4fec-b4c8-1dd70f292e62)

**Comment by davepagurek** [comment]
Previously I added this bit of code to exclude multiline code blocks from having their HTML escaped:
https://github.com/processing/p5.js-website/blob/c4eea2e2a4162b8cec7854733194c6ede183bd2e/src/pages/_utils.ts#L236-L238

So it looks like after that is where it tries to escape the contents of inline code blocks. Since in the original mdx file, it's node escaped at all (e.g. `<code>&&</code>`) but it ends up as `<code>&amp;amp;&amp;amp;</code>`, it looks like maybe this bit of code is double-escaping?
https://github.com/processing/p5.js-website/blob/c4eea2e2a4162b8cec7854733194c6ede183bd2e/src/pages/_utils.ts#L240-L245

**Comment by shibomb** [comment]
I tried the following in my local environment.
```
 $("code").each(function () {
    return; // skip all process
```
And it displayed well. (see Green Boxed in attached image.)
(I haven't checked the effect on other parts of the page)

It seems to be double-escaped, as you guessed.

![スクリーンショット 2024-10-18 17 58 06](https://github.com/user-attachments/assets/9ae95fb4-46ed-4ac8-ab4a-b2acb58d657f)

The red boxed is still wrong.
The mdx file is already wrong.

https://github.com/processing/p5.js-website/blob/c4eea2e2a4162b8cec7854733194c6ede183bd2e/src/content/reference/en/p5/types/Boolean.mdx?plain=1#L142-L143

Maybe there is a bug in the process of generating the mdx file.
For example, “<” is recognized as the beginning of a tag...

**Comment by shibomb** [comment]
Additional information.

> (I haven't checked the effect on other parts of the page)
>
Checked other parts of the page and the following problem recurred:
"bug: need to escape html tags in reference documentation #95 "

So the “skip all” I tried was not working.

**Comment by davepagurek** [comment]
You're right, we'll need to fix that before looking at how it gets converted to mdx.

This is the correct input in the p5 docs: https://github.com/processing/p5.js/blob/5a7129b21da8a9dc85e47d6b8f7d066f4e770d59/src/core/reference.js#L592

It looks like other parts of the p5 codebase manually html-escape symbols in backtick cod blocks: https://github.com/processing/p5.js/blob/78c4442d9cc77e849f3cdea3509fff99e3a26301/src/io/p5.XML.js#L17

It seems like in `src/scripts/out/data-p5/data.json`, the output of Yuidoc, it already is incorrect:
![image](https://github.com/user-attachments/assets/0d24b02a-5d0f-46f2-b9bf-c7e1bf34f0f7)

It looks like a [Yuidoc preprocessor](https://yui.github.io/yuidoc/args/index.html#ex-preprocessor) in `docs/preprocessor.js` in the p5 repo is responsible for converting these to Markdown, but it *decodes* the HTML special characters: https://github.com/processing/p5.js/blob/5a7129b21da8a9dc85e47d6b8f7d066f4e770d59/docs/preprocessor.js#L261-L265

<details><summary>(For reference, here's how that gets used)</summary>

We do try to specify this file via a config file:
https://github.com/processing/p5.js-website/blob/c4eea2e2a4162b8cec7854733194c6ede183bd2e/yuidoc.json#L6

Which we pass to yuidoc here:
https://github.com/processing/p5.js-website/blob/c4eea2e2a4162b8cec7854733194c6ede183bd2e/src/scripts/parsers/reference.ts#L25

This config file does seem to be read because if I use a branch of p5 that doesn't have that preprocessor file, `npm run build:reference` throws an error as expected.

</details>

I wonder if this was to make sure tags that we want to be rendered as HTML, e.g. `<table>` were getting escaped otherwise?

So there are a few problems here that need fixing:
- HTML escaping is used inconsistently in the p5 codebase
  - I think we should standardize on **not manually HTML-escaping code blocks** because in Markdown, this should not be necessary (only *outside* code blocks would it treat it like real HTML.)
- The escaping done in the preprocessor does not seem to be working correctly
  - It's a little complicated because we only want to escape the contents of code blocks
  - The first thing I'd try is just not decoding the entities from the markdown parser. Maybe it already does it correctly if we remove that? Otherwise, we'll need to just find the `<code>` tags and escape the contents of those.

I think both of those need to be addressed in the main p5 repo before being handled here. Those can be tested in that repo via `npm run docs` and then checking the output in `docs/reference/data.json`.

**Comment by shibomb** [comment]
@davepagurek 
I have created a pull request for a proposed solution for double-escape. #606 
Please check it, if you need it.
