### ISSUE TITLE
getting started is either incpmplete or misleading (open sketch in your browser part)

### ISSUE THREAD

**Issue by teo1978** [processing/p5.js-website#84]
At http://p5js.org/get-started/

> Open a web browser. Type:
> **localhost**/path/to/your/index.html 
> in the address bar to view your sketch.

Does it mean **localhost** *literally*?? If that is the case, then that's assuming you have a web server running locally on your computer. If that is required, it should be mentioned, and some links to the most popular and easily to install web servers (perhaps xampp) should be given. You can't expect the typical user to already have a local web server installed, nor to automatically figure out that he needs to install and run one.
Or am I missing something and SublimeText includes one, or even the p5.js does?? If that is the case, that's also worth mentioning.

If, instead, by */localhost/path/to/your/index.html* you mean */the/file/path/to/your/html*, that is, if all you need is open the html file in your browser, then you should use a different example path that does not contain *localhost*, as that is very misleading, and also, you could rephrase it as something like "just open the index.html file in your browser by double clicking on  it in your file manager or by typing '...' in your browser" or something like that, and **MOST IMPORTANTLY** the address should include file:///, as it won't work otherwise.

**Comment by lmccart** [comment]
thanks @teo1978 for pointing out this error, this was an oversight due to porting some instructions we used in class where the students had all put their folders within their WebDocuments folder. this isn't necessary and we did really mean `/the/file/path/to/your/html`. your suggestion to include the instruction about double clicking is right on. I will make the change as soon as I get a chance, or feel free to submit a PR if you like.

the intensity of your post leads me to think this may have caused you some frustration, and for that I apologize. please keep in mind this is a completely volunteer driven project, and we are trying to keep the community feeling as open and inclusive as possible, so being sensitive of your tone will go a long way toward making everyone feel welcome and motivated.

**Comment by teo1978** [comment]
> the intensity of your post leads me to think this may have caused you some frustration, and for that I apologize.

Not at all; actually  I didn't  mean my post to be "intense" at all, so I am the one who apologizes.

**Comment by blindfish3** [comment]
This issue has reoccurred: the instructions again reference localhost/

**Comment by limzykenneth** [comment]
It seems PR #109 reverted the changes done here, I'm not sure if that's by accident or intended. I'll submit a PR to fix this tomorrow if it isn't intended. Cheers.

**Comment by lmccart** [comment]
ah sorry, i dont know how it got lost, but def not intended. wonderful if you can submit a pr @limzykenneth, thank you!
