### ISSUE TITLE
Search API unresponsive sometimes

### ISSUE THREAD

**Issue by justinpeake** [processing/p5.js-website#91]
I've noticed that sometimes, recently after looking at the keyPressed() objects, the pleasantly large Search API box is unresponsive to typing after 1 search. I'm usually in Firefox. Haven't tested in Chrome.

**Comment by limzykenneth** [comment]
I can confirm for Safari and Chrome. I think what's happening is that the second example sketch is set to nullify all default action of the keyboard with `return false;`. I'm not sure how best to solve this but maybe sandbox it somehow but I suppose it will need a more fundamental change to how the examples are generated.

Alternatively, we can change the code into this:

```
var value = 0;

function draw() {
  fill(value);
  rect(25, 25, 50, 50);
}
function keyPressed() {
  if (keyCode === LEFT_ARROW) {
    value = 255;
    return false; // prevent any default behavior
  } else if (keyCode === RIGHT_ARROW) {
    value = 0;
    return false; // prevent any default behavior
  }
}
```

That way, only the left and right arrow keys won't exhibit any default behaviour.

Or alternatively, we can remove the `return false;` altogether as personally I don't really see how including it in the example can be useful for the user. The documentation already mentioned this anyway.

**Comment by lmccart** [comment]
thanks for looking into this. I think it is useful to have a return false example for people that don't understand the note in the description. my suggestion is this: remove the `return false;` line from the second example. then let's add a third, very minimal example just to demonstrate the use of `return false` ,using the `class="norender"` flag on that example so the code is not actually run. 

@limzykenneth do you want to work on this? otherwise I can fix on my next round of doc updates. if you do want to tackle it, info on adding and modifying reference examples is here: https://github.com/processing/p5.js/wiki/Inline-documentation#adding-example-code

**Comment by limzykenneth** [comment]
That's a better idea, I'll work on it~ Cheers

**Comment by lmccart** [comment]
great, thanks! let me know if you have any questions about the example / doc building processing.

**Comment by lmccart** [comment]
closed with https://github.com/processing/p5.js/pull/919
